### PR TITLE
seperate reports with errors better. upgrade loop.py

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/cip_api_reports/16)

### CODE REVIEW

**Comment by woook** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[gel_report_config.py, line 29 at r1](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16#-KyH5zFN5oGMgR_EyL18:-KyH5zFN5oGMgR_EyL19:b-pykoub) ([raw file](https://github.com/moka-guys/cip_api_reports/blob/5b903d0494be6f58a775ebef38508c1f07017d3d/gel_report_config.py#L29)):*
> ```Python
> 
> # warning message if there is an error reported when generating the report
> warning_message = "Warning!Error making the report for GEL ID %s.\nIf issue continues for this sample contact GEL Helpdesk @ ge-servicedesk@genomicsengland.co.uk\nReport will be generated in the subfolder \"reports_with_errors\"\nError message = "
> ```

Who is this error message for? Do we want the user to contact GeL rather than us in the first instance? or should we discuss internally before contacting GeL?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16)*

**Comment by aledj2** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[gel_report_config.py, line 29 at r1](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16#-KyH5zFN5oGMgR_EyL18:-KyH7Rc513T3Pi1ouJ2Q:b4dpr7v) ([raw file](https://github.com/moka-guys/cip_api_reports/blob/5b903d0494be6f58a775ebef38508c1f07017d3d/gel_report_config.py#L29)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Who is this error message for? Do we want the user to contact GeL rather than us in the first instance? or should we discuss internally before contacting GeL?
</blockquote></details>

this will be displayed in an message box in the moka front end to whoever is generating the repotrt. binfx or DNA lab

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16)*

**Comment by woook** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[gel_report_config.py, line 29 at r1](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16#-KyH5zFN5oGMgR_EyL18:-KyH7oG_51zTJPo2Kx33:b-7v6al2) ([raw file](https://github.com/moka-guys/cip_api_reports/blob/5b903d0494be6f58a775ebef38508c1f07017d3d/gel_report_config.py#L29)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

this will be displayed in an message box in the moka front end to whoever is generating the repotrt. binfx or DNA lab
</blockquote></details>

So should we change the contact to someone internal?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16)*

**Comment by aledj2** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[gel_report_config.py, line 29 at r1](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16#-KyH5zFN5oGMgR_EyL18:-KyH7vMXfdaQgkly03-1:b-9nvc5p) ([raw file](https://github.com/moka-guys/cip_api_reports/blob/5b903d0494be6f58a775ebef38508c1f07017d3d/gel_report_config.py#L29)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

So should we change the contact to someone internal?
</blockquote></details>

wait to see if it'll integrate into the tracking system

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16)*

**Comment by woook** [comment]
Reviewed 2 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[loop.py, line 2 at r1](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16#-KyH8gA3DjbIvBJakX02:-KyH8gA3DjbIvBJakX03:bjhzfy4) ([raw file](https://github.com/moka-guys/cip_api_reports/blob/5b903d0494be6f58a775ebef38508c1f07017d3d/loop.py#L2)):*
> ```Python
> # list of probands
> list_of_GELIDS=['50003384', '50001343', '50004169', '50002418', '50004234', '50003398', '50002250', '50004174', '50004235', '50004232', '50002730', '50002721', '50003319', '50002422', '50003799', '50003808', '50004024', '50004026', '50004182', '50004661', '50004719', '50002560', '50003506', '50003796', '50003807', '50003810', '50004176', '50003587', '50002771', '50004237', '50003510', '50003515', '50003586', '50004205', '50002774', '50003318', '50003773', '50004058', '50003507', '50003018', '50002021', '50003754', '50003516', '50001871', '50002442', '50001829', '50002045', '50002423', '50002040', '50004022', '50003388', '50004203', '50003760', '50002020', '50004011', '50002249', '50003554', '50003385', '50003382', '50002554', '50001828', '50004185', '50003316', '50003583', '50002421']
> ```

This is ok for now, but let's see if we can move away from hard-coded inputs & outputs in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16)*

**Comment by woook** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[gel_report_config.py, line 29 at r1](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16#-KyH5zFN5oGMgR_EyL18:-KyH9Br5cD6uv_Lwl31o:bw8yc57) ([raw file](https://github.com/moka-guys/cip_api_reports/blob/5b903d0494be6f58a775ebef38508c1f07017d3d/gel_report_config.py#L29)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

wait to see if it'll integrate into the tracking system
</blockquote></details>

Please could email address to mokaguys for now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16)*

**Comment by woook** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gel_report_config.py, line 29 at r2](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16#-KyHBGcDIlmkzQuW887p:-KyHBGcDIlmkzQuW887q:b-d2ghek) ([raw file](https://github.com/moka-guys/cip_api_reports/blob/766517f33785c9cfa1f79371d04e322105f6501e/gel_report_config.py#L29)):*
> ```Python
> 
> # warning message if there is an error reported when generating the report
> warning_message = "Warning!Error making the report for GEL ID %s.\nIf issue continues for this sample contact bioinformatics team at gst-tr.mokaguys@nhs.net\nReport will be generated in the subfolder \"reports_with_errors\"\nError message = "
> ```

Capitalise bioinformatics!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16)*

**Comment by woook** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16)*

**Comment by woook** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/cip_api_reports/16#-:-KyHDNeawONvow9ucwio:bnfp4nl)*

**Pull request merged**
